// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqowvkejvunphibxeozc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlxb3d2a2VqdnVucGhpYnhlb3pjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMDM5NjgsImV4cCI6MjA2NDY3OTk2OH0.dYivbttjCCleGCTbEPj8YaP4O7ZU8dAjjWg4kj7L1cU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);